### PR TITLE
Bunch of changes

### PR DESCRIPTION
**Pull request by gigaraptor**
- QuestGame removed and replaced with Main.cpp
- Banner loaded from data file now
- header file added to save time including and to share functions across
files
- include locking now present
- os independent screen clearing and pauses
- new init function initialises the game
- deinit prototype

### CODE REVIEW

**Comment by samis** [comment]
You. I like you. Good job.

**Comment by aelzenaar** [comment]
The include guards should be in the header and different for each file. See https://en.wikipedia.org/wiki/Include_guard - surround basic.h with:

    #ifndef BASIC_H_INCLUDED
    #define BASIC_H_INCLUDED
    .... contents ....
    #endif

**Comment by gigaraptor** [comment]
Yeah you are right. I was in a bit of a rush when I wrote it so there will be some little issues like getting the defines the wrong way round .

**Comment by aelzenaar** [comment]
I pushed a changeset to the main repo to fix it anyways :)

**Pull request merged**
